### ISSUE TITLE
java.lang.VerifyError on LocationGooglePlayServicesProvider in Runtime.

### ISSUE THREAD

**Issue by GMuniz** [mrmans0n/smart-location-lib#105]
```
FATAL EXCEPTION: main
java.lang.VerifyError: io/nlopez/smartlocation/location/providers/LocationGooglePlayServicesProvider
    at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.<init>(LocationGooglePlayServicesWithFallbackProvider.java:32)
    at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:60)
```
My app is actually using GooglePlayServices, and also using fused location.

The call I'm making from activity:
```java
final Location lastLocation = SmartLocation.with(this)
			    .location()
			    .getLastLocation();
```

- Using Android Studio with Gradle.

Java version:
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
```

**Comment by rohanmahale** [comment]
Which Android version is this? API level?

**Comment by GMuniz** [comment]
This happened while running in marshmallow. API 23.

Tested on a real Nexus 6.

**Comment by zahid--ali** [comment]
@GMuniz  have you found any solution to this

**Comment by PingForward** [comment]
@zahid--ali @GMuniz 
Use specified provider `SmartLocation.with(this).location(new LocationGooglePlayServicesWithFallbackProvider(this)).getLastLocation();`
But I have problem getting last location with this provider. Use `new LocationManagerProvider()` it works
