### ISSUE TITLE
java.lang.IllegalArgumentException: no providers found for criteria 

### ISSUE THREAD

**Issue by droidster** [mrmans0n/smart-location-lib#108]
My app is crashing on this piece of code.

```java
LocationAccuracy locationAccuracy;
if (locationManager.isProviderEnabled(LocationManager.GPS_PROVIDER)){
	locationAccuracy = LocationAccuracy.HIGH;
} else{
	locationAccuracy = LocationAccuracy.MEDIUM;
}

LocationParams locationParams = (new LocationParams.Builder()).setAccuracy(locationAccuracy)
				.setDistance(LOCATION_UPDATE_DISTANCE_METRES)
				.setInterval(LOCATION_UPDATE_INTERVAL_MILLISECONDS).build();

//crashing on this line.
SmartLocation.with(this).location(new LocationManagerProvider()).config(locationParams).start(this);
```

Is it an issue with the library or with the way I'm using it?

**Comment by mtrakal** [comment]
Same for us on version 3.2.1

`Fatal Exception: java.lang.IllegalArgumentException: no providers found for criteria
       at android.os.Parcel.readException(Parcel.java:1429)
       at android.os.Parcel.readException(Parcel.java:1379)
       at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:684)
       at android.location.LocationManager._requestLocationUpdates(LocationManager.java:664)
       at android.location.LocationManager.requestSingleUpdate(LocationManager.java:925)
       at io.nlopez.smartlocation.location.providers.LocationManagerProvider.start(LocationManagerProvider.java:48)
       at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.fallbackToLocationManager(LocationGooglePlayServicesWithFallbackProvider.java:88)
       at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.onConnectionSuspended(LocationGooglePlayServicesWithFallbackProvider.java:75)
       at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.onConnectionSuspended(LocationGooglePlayServicesProvider.java:187)
       at com.google.android.gms.common.internal.zzk.zzqQ(Unknown Source)
       at com.google.android.gms.common.api.internal.zzj.zza(Unknown Source)
       at com.google.android.gms.common.api.internal.zzg.begin(Unknown Source)
       at com.google.android.gms.common.api.internal.zzl.zza(Unknown Source)
       at com.google.android.gms.common.api.internal.zzc.onConnectionSuspended(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:5096)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by rohannexialabs** [comment]
Any update on this, I am getting huge number of crashes due to this issue.

**Comment by droidster** [comment]
@mtrakal @rohannexialabs 

Guys, I was finally able to find a solution for this. I was able to reproduce this crash on a device without Google Play services (that's when I use this library) with location services disabled. Not just the GPS turned off but the location services on the device switched off so can't even get the location from network.

Just added a check before doing other stuff.

```
private void startLegacyLocationUpdates(){
	// If network provider is not enabled, do nothing.
	if (!locationManager.isProviderEnabled(LocationManager.NETWORK_PROVIDER)) {
            return;
	}
        
   // set criteria, build params and start updates.
}
```

In onCreate I do this check to show a dialog to take the user to the location services settings. Hope this helps.

**Comment by mtrakal** [comment]
Thanks for search solution :+1: 

But I think, that this behaviour should handle a lib, not programmers on every places where they want to use location :). But maybe I'm wrong...

**Comment by droidster** [comment]
I think it gives devs an option to show users a message in case of this scenario, but maybe a callback in case no providers are available would be nice, depends on what the thinking was. :)

This would be a better approach as mentioned in the readme, so we don't have to deal with location managers:

```
// Check if Network is available
SmartLocation.with(context).location().state().isNetworkAvailable();
```
