### ISSUE TITLE
IllegalArgumentException: no providers found for criteria

### ISSUE THREAD

**Issue by mtrakal** [mrmans0n/smart-location-lib#118]
```
 SmartLocation.with(getApplicationContext()).location()
                                        .oneFix()
                                        .start(mOnLocationUpdatedListener);
```

```
Fatal Exception: java.lang.IllegalArgumentException: no providers found for criteria
       at android.os.Parcel.readException(Parcel.java:1442)
       at android.os.Parcel.readException(Parcel.java:1389)
       at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:659)
       at android.location.LocationManager._requestLocationUpdates(LocationManager.java:690)
       at android.location.LocationManager.requestSingleUpdate(LocationManager.java:951)
       at io.nlopez.smartlocation.location.providers.LocationManagerProvider.start(LocationManagerProvider.java:48)
       at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.fallbackToLocationManager(LocationGooglePlayServicesWithFallbackProvider.java:88)
       at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.onConnectionSuspended(LocationGooglePlayServicesWithFallbackProvider.java:75)
       at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.onConnectionSuspended(LocationGooglePlayServicesProvider.java:187)
       at com.google.android.gms.common.internal.zzk.zzqA(Unknown Source)
       at com.google.android.gms.internal.zzmg.zza(Unknown Source)
       at com.google.android.gms.internal.zzmd.begin(Unknown Source)
       at com.google.android.gms.internal.zzmi.zza(Unknown Source)
       at com.google.android.gms.internal.zzlz.onConnectionSuspended(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:4787)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Have no idea when it is made, it's from our crashlytics and just this part of exception. But it's often.

**Comment by djrsousa** [comment]
I'm also getting this error and it's quite often. I guess that this maybe could be fixed if there was a default statement in the switch case of the getProvider(LocationParams params) method of the LocationManagerProvider class. (l. 77 https://github.com/mrmans0n/smart-location-lib/blob/master/library/src/main/java/io/nlopez/smartlocation/location/providers/LocationManagerProvider.java).

**Comment by yesidlazaro** [comment]
hello,
 can you release a new version of this issue , our app is getting a lot of crashes because it.
