### ISSUE TITLE
java.lang.NoClassDefFoundError: io.nlopez.smartlocation.SmartLocation after Making JAR file

### ISSUE THREAD

**Issue by faizulhaque-tp** [mrmans0n/smart-location-lib#127]
After making JAR flie, i am getting 
java.lang.NoClassDefFoundError: io.nlopez.smartlocation.SmartLocation
03-26 12:36:15.421: W/dalvikvm(25576): threadid=1: thread exiting with uncaught exception (group=0x4197cc98)
03-26 12:36:15.421: W/dalvikvm(25576): threadid=1: uncaught exception occurred
03-26 12:36:15.421: W/System.err(25576): java.lang.NoClassDefFoundError: io.nlopez.smartlocation.SmartLocation
03-26 12:36:15.424: W/System.err(25576): 	at com.example.test.com.org.MainActivity.showLocation(MainActivity.java:47)
03-26 12:36:15.425: W/System.err(25576): 	at com.example.test.com.org.MainActivity.access$0(MainActivity.java:45)
03-26 12:36:15.425: W/System.err(25576): 	at com.example.test.com.org.MainActivity$1.onClick(MainActivity.java:37)
03-26 12:36:15.425: W/System.err(25576): 	at android.view.View.performClick(View.java:4463)
03-26 12:36:15.425: W/System.err(25576): 	at android.view.View$PerformClick.run(View.java:18774)
03-26 12:36:15.425: W/System.err(25576): 	at android.os.Handler.handleCallback(Handler.java:808)
03-26 12:36:15.425: W/System.err(25576): 	at android.os.Handler.dispatchMessage(Handler.java:103)
03-26 12:36:15.425: W/System.err(25576): 	at android.os.Looper.loop(Looper.java:193)
03-26 12:36:15.425: W/System.err(25576): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
03-26 12:36:15.425: W/System.err(25576): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-26 12:36:15.425: W/System.err(25576): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-26 12:36:15.425: W/System.err(25576): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
03-26 12:36:15.426: W/System.err(25576): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
03-26 12:36:15.426: W/System.err(25576): 	at dalvik.system.NativeStart.main(Native Method)
03-26 12:36:15.426: W/dalvikvm(25576): threadid=1: calling UncaughtExceptionHandler
03-26 12:36:15.429: E/AndroidRuntime(25576): FATAL EXCEPTION: main
03-26 12:36:15.429: E/AndroidRuntime(25576): Process: com.example.test.com.org, PID: 25576
03-26 12:36:15.429: E/AndroidRuntime(25576): java.lang.NoClassDefFoundError: io.nlopez.smartlocation.SmartLocation
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at com.example.test.com.org.MainActivity.showLocation(MainActivity.java:47)
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at com.example.test.com.org.MainActivity.access$0(MainActivity.java:45)
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at com.example.test.com.org.MainActivity$1.onClick(MainActivity.java:37)
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at android.view.View.performClick(View.java:4463)
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at android.view.View$PerformClick.run(View.java:18774)
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at android.os.Handler.handleCallback(Handler.java:808)
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at android.os.Handler.dispatchMessage(Handler.java:103)
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at android.os.Looper.loop(Looper.java:193)
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
03-26 12:36:15.429: E/AndroidRuntime(25576): 	at dalvik.system.NativeStart.main(Native Method)

could any help me out with this?
i am making JAR file to make it work on eclipse.

**Comment by Midhilaj** [comment]
java.lang.NoClassDefFoundError: io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider
                                                                                       at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.<init>(LocationGooglePlayServicesWithFallbackProvider.java:32)
                                                                                       at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:59)
                                                                                       at com.shopify.sample.address.fragment.ViewAddressFragment.onCreateView(ViewAddressFragment.java:290)
                                                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248)
                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
                                                                                       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                                       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
                                                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
                                                                                       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
                                                                                       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2034)
                                                                                       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                                                       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                                       at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                                       at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                                       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
                                                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1212)
                                                                                       at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:1552)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
                                                                                       at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
                                                                                       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1391)
                                                                                       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                   	at android.view.ViewGroup.measureChildWithMargins(ViewGr

**Comment by Midhilaj** [comment]
java.lang.NoClassDefFoundError: io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider
                                                                                       at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.<init>(LocationGooglePlayServicesWithFallbackProvider.java:32)
                                                                                       at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:59)
                                                                                       at com. milla.sample.address.fragment.ViewAddressFragment.onCreateView(ViewAddressFragment.java:290)
                                                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248)
                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
                                                                                       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                                       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
                                                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
                                                                                       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
                                                                                       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2034)
                                                                                       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                                                       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                                       at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                                       at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                                       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
                                                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1212)
                                                                                       at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:1552)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
                                                                                       at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
                                                                                       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1391)
                                                                                       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                       at android.view.View.measure(View.java:18804)
                                                                                   	at android.view.ViewGroup.measureChildWithMargins(ViewGr

**Comment by Midhilaj** [comment]
I fixed the problem by adding this to build.gradle:
compile 'com.google.android.gms:play-services-location:11.8.0'
