### ISSUE TITLE
NullPointerException in GeofencingGooglePlayServicesProvider.java:247

### ISSUE THREAD

**Issue by erf** [mrmans0n/smart-location-lib#130]
I received an crash report from Crashlytics now with the following information:

```
Fatal Exception: java.lang.NullPointerException
       at io.nlopez.smartlocation.geofencing.providers.GeofencingGooglePlayServicesProvider$GeofencingService.onHandleIntent(GeofencingGooglePlayServicesProvider.java:247)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

This bug seems strange to me as i am NOT using any geofencing functionalty (!)

The code referenced is:

```
for (Geofence geofence : geofencingEvent.getTriggeringGeofences()) {
```

**Comment by lvaizer** [comment]
same here
