### ISSUE TITLE
Marshmallow runtime permissions

### ISSUE THREAD

**Issue by melihcolpan** [mrmans0n/smart-location-lib#131]
Is there any native check for runtime permissions?

**Comment by joxad** [comment]
Hi, I had a crash if no permission checked done. 

It could be nice to do something like this :

```java
 /**
     * @return request handler for location operations
     */
    public LocationControl location() throws NoPermissionAcceptedException {
        if (ContextCompat.checkSelfPermission(context, android.Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            throw new NoPermissionAcceptedException(android.Manifest.permission.ACCESS_COARSE_LOCATION);
        }
        return location(new LocationGooglePlayServicesWithFallbackProvider(context));
    }


public class NoPermissionAcceptedException extends Throwable {

    public NoPermissionAcceptedException(String permission) {
        super(permission);
    }

}

```

to avoid the crash if no permission accepted.

**Comment by hurzl** [comment]
I Have several apps that crash with something like

```
09-08 23:50:53.592 27012 27012 E AndroidRuntime: java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at com.google.android.gms.location.internal.ab.a(Unknown Source)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at com.google.android.gms.location.internal.af.a(Unknown Source)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at com.google.android.gms.location.internal.aj.a(Unknown Source)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at com.google.android.gms.location.internal.i.a(Unknown Source)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at com.google.android.gms.location.internal.i.a(Unknown Source)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at com.google.android.gms.b.aan.b(Unknown Source)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at com.google.android.gms.b.abd.c(Unknown Source)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at com.google.android.gms.b.abd.b(Unknown Source)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at com.google.android.gms.b.aby.b(Unknown Source)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at com.google.android.gms.b.abs.b(Unknown Source)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at com.google.android.gms.location.internal.h.a(Unknown Source)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.startUpdating(SourceFile:136)
09-08 23:50:53.592 27012 27012 E AndroidRuntime:        at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.onConnected(SourceFile:177)
```
