### ISSUE TITLE
Google Play services 9.6.1 compatibility (Firebase)

### ISSUE THREAD

**Issue by pollaken** [mrmans0n/smart-location-lib#171]
Hi,

I am trying to get Firebase to work, which uses Google Play services 9.6.1 and the library stopped working. I am getting this error when running the app:

`Theme: themes:{default=overlay:system, iconPack:com.baranovgroup.nstyle, fontPkg:com.baranovgroup.nstyle, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
                                                               java.lang.NoClassDefFoundError: io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider
                                                                   at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.<init>(LocationGooglePlayServicesWithFallbackProvider.java:32)
                                                                   at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:59)
                                                                   at myApplication.SplashScreen.onPermissionsGranted(mySplashScreen.java:71)
                                                                   at myApplication.RuntimePermissionsActivity.requestAppPermissions(RuntimePermissionsActivity.java:95)
                                                                   at myApplication.mySplashScreen.access$001(mySplashScreen.java:24)
                                                                   at myApplication.mySplashScreen.onCreate(mySplashScreen.java:37)
                                                                   at android.app.Activity.performCreate(Activity.java:6251)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Firebase requires me to add the following:

```
buildscript {
    dependencies {
        classpath 'com.google.gms:google-services:3.0.0'

    }
}
```

and 

`apply plugin: 'com.google.gms.google-services'`

maybe this is somehow causing problems.

Thanks.

**Comment by irfaan008** [comment]
No its not because of firebase. I was using it as expected till I was in Google play service version 9.4.0. Today only updated to 9.6.1 and facing the same issue. So I am sure this is not cause of Firebase.

**Comment by pollaken** [comment]
Yes you are right, I have downloaded manually the library and changed Google Play services version to 9.6.1 in gradle file and it works now.
