### ISSUE TITLE
Google play service 9.6.1 issues

### ISSUE THREAD

**Issue by irfaan008** [mrmans0n/smart-location-lib#172]
Today I updated my code to run Google play services and firebase on 9.6.1 and I started getting error as shown in screenshot:

`10-13 12:47:05.075 29782-29782/com.adcoretechnologies.rny E/dalvikvm: Could not find class 'com.google.android.gms.location.internal.zzq$1', referenced from method com.google.android.gms.location.internal.zzq.zza
10-13 12:47:05.105 29782-29782/com.adcoretechnologies.rny E/UncaughtException: java.lang.AbstractMethodError: abstract method not implemented
                                                                                   at com.google.android.gms.common.api.Api$zza.zza(Unknown Source)
                                                                                   at com.google.android.gms.common.api.GoogleApiClient$Builder.zza(Unknown Source)
                                                                                   at com.google.android.gms.common.api.GoogleApiClient$Builder.zzaqe(Unknown Source)
                                                                                   at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
                                                                                   at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.init(LocationGooglePlayServicesProvider.java:68)
                                                                                   at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.init(LocationGooglePlayServicesWithFallbackProvider.java:45)
                                                                                   at io.nlopez.smartlocation.SmartLocation$LocationControl.<init>(SmartLocation.java:173)
                                                                                   at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:67)
                                                                                   at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:59)
                                                                                   at com.adcoretechnologies.rny.home.seller.FragmentDashboard.onMapReady(FragmentDashboard.java:179)
                                                                                   at com.google.android.gms.maps.SupportMapFragment$zza$1.zza(Unknown Source)
                                                                                   at com.google.android.gms.maps.internal.zzt$zza.onTransact(Unknown Source)
                                                                                   at android.os.Binder.transact(Binder.java:361)
                                                                                   at wy.a(:com.google.android.gms.DynamiteModulesB:82)
                                                                                   at maps.ad.t$5.run(Unknown Source)
                                                                                   at android.os.Handler.handleCallback(Handler.java:733)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                                                   at dalvik.system.NativeStart.main(Native Method)`

**Comment by khuranakaran** [comment]
Having same problem, did you find any solution for it ?

**Comment by irfaan008** [comment]
Library is already updated for latest version. Kindly use the latest version of library.
