### ISSUE TITLE
IllegalArgumentException: provider==null

### ISSUE THREAD

**Issue by kamilwlf** [mrmans0n/smart-location-lib#19]
sometimes there is ```IllegalArgumentException: provider==null```

error occurs on older devices
```
java.lang.IllegalArgumentException: provider==null
at android.location.LocationManager.isProviderEnabled(LocationManager.java:1136)
at io.nlopez.smartlocation.SmartLocationService.startOldSchoolLocation(SmartLocationService.java:161)
at io.nlopez.smartlocation.SmartLocationService.access$200(SmartLocationService.java:27)
at io.nlopez.smartlocation.SmartLocationService$1.run(SmartLocationService.java:137)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:153)
at android.app.ActivityThread.main(ActivityThread.java:5071)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mrmans0n** [comment]
This shouldn't be a problem with the 3.0.0 release.
