### ISSUE TITLE
Issue with Google Services

### ISSUE THREAD

**Issue by andriaripratama** [mrmans0n/smart-location-lib#201]
Hi,

Recently, I added com.google.gms:google-services:3.0.0 for using Firebase services such as Notification and Analytics.

When I build, my app instantly forces close with these errors:

`FATAL EXCEPTION: main
                                                                                         Process: com.kreatifin.mobile.monitoringpinjaman, PID: 13239
                                                                                         java.lang.NoSuchMethodError: No static method zzdD(Ljava/lang/String;)Z in class Lcom/google/android/gms/common/util/zzv; or its super classes (declaration of 'com.google.android.gms.common.util.zzv' appears in /data/app/com.kreatifin.mobile.monitoringpinjaman-1/split_lib_dependencies_apk.apk:classes26.dex)
                                                                                             at com.google.firebase.FirebaseOptions.<init>(Unknown Source)
                                                                                             at com.google.firebase.FirebaseOptions.fromResource(Unknown Source)
                                                                                             at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                             at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                                             at android.content.ContentProvider.attachInfo(ContentProvider.java:1716)
                                                                                             at android.content.ContentProvider.attachInfo(ContentProvider.java:1685)
                                                                                             at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                                             at android.app.ActivityThread.installProvider(ActivityThread.java:5559)
                                                                                             at android.app.ActivityThread.installContentProviders(ActivityThread.java:5154)
                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5094)
                                                                                             at android.app.ActivityThread.access$1600(ActivityThread.java:177)
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                             at android.os.Looper.loop(Looper.java:145)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)`

Then I troubleshoot one by one, I deleted this library (io.nlopez.smartlocation:library:3.3.1) and the problem solved. Can you explain what happen with this issue and how to fix it?

Thank you.

**Comment by alexnix** [comment]
+1
