### ISSUE TITLE
Incompatible with google play services 11

### ISSUE THREAD

**Issue by mnayef** [mrmans0n/smart-location-lib#204]
Get the error 
`                                                                        java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzq, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
                                                                            at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
                                                                            at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.init(LocationGooglePlayServicesProvider.java:83)
                                                                            at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.init(LocationGooglePlayServicesWithFallbackProvider.java:45)
                                                                            at io.nlopez.smartlocation.SmartLocation$LocationControl.<init>(SmartLocation.java:173)
                                                                            at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:67)
                                                                            at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:59)
                                                                            at com.appsmodern.alaovia.common.MyApplication.getLocation(MyApplication.java:76)
                                                                            at com.appsmodern.alaovia.common.MyApplication.onCreate(MyApplication.java:49)
                                                                            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6422)
                                                                            at android.app.ActivityThread.access$1800(ActivityThread.java:229)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

when i use google serivce 11

**Comment by ofirmiron** [comment]
Hello,
I just made a pull request that provides compatibility with google play services 11. Hopefully it will be integrated to the main branch soon.

**Comment by irfaan008** [comment]
seems @mnayef95 is not much active on this. It still doesn't support the latest play service version

**Comment by AlexioVay** [comment]
Still no solution to this?

**Comment by mrmans0n** [comment]
Ehm, it's already on prod? play services 11.0.2 is supported

**Comment by AlexioVay** [comment]
Do you mean 11.0.4? I use firebase services where no 11.0.2 exists but 11.0.4. 

I can only make it work with firebase services 10.2.0 and your lib version 3.3.1.

**Comment by mrmans0n** [comment]
you can always exclude the gradle dependency from the library, so yours is
used instead. that should work, the api hasn't changed.
