### ISSUE TITLE
FATAL EXCEPTION with  Google Play Services 6.5.87

### ISSUE THREAD

**Issue by kamilwlf** [mrmans0n/smart-location-lib#21]
FATAL EXCEPTION  http://stackoverflow.com/questions/27372638/android-play-services-6-5-locationclient-is-missing
```
12-11 09:10:36.758  26218-26218/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: xxx, PID: 26218
    java.lang.NoClassDefFoundError: com.google.android.gms.location.LocationClient
            at io.nlopez.smartlocation.SmartLocationService.initLocation(SmartLocationService.java:90)
            at io.nlopez.smartlocation.SmartLocationService.onCreate(SmartLocationService.java:75)
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2558)
            at android.app.ActivityThread.access$1800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mrmans0n** [comment]
This should be fixed with the 3.0.0 version.
