### ISSUE TITLE
Class Not Found Exception 

### ISSUE THREAD

**Issue by rutvikbhatt9** [mrmans0n/smart-location-lib#222]
11-03 13:17:38.460 7785-7785/com.wmt.android.sterlingaccurisapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.wmt.android.sterlingaccurisapp, PID: 7785
                                                                                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
                                                                                      at com.google.android.gms.location.zzs.zza(Unknown Source:0)
                                                                                      at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source:112)
                                                                                      at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.init(LocationGooglePlayServicesProvider.java:83)
                                                                                      at io.nlopez.smartlocation.SmartLocation$LocationControl.<init>(SmartLocation.java:173)
                                                                                      at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:67)
                                                                                      at com.wmt.android.sterlingaccurisapp.fragment.LocateLabListFragment.startLocation(LocateLabListFragment.java:460)
                                                                                      at com.wmt.android.sterlingaccurisapp.fragment.LocateLabListFragment.permissionGiven(LocateLabListFragment.java:393)
                                                                                      at com.wmt.android.sterlingaccurisapp.fragment.BaseMultiPermissionFragment.onPermissionsChecked(BaseMultiPermissionFragment.java:87)
                                                                                      at com.karumi.dexter.listener.multi.CompositeMultiplePermissionsListener.onPermissionsChecked(CompositeMultiplePermissionsListener.java:54)
                                                                                      at com.karumi.dexter.DexterInstance$1.run(DexterInstance.java:334)
                                                                                      at com.karumi.dexter.MainThread.execute(MainThread.java:32)
                                                                                      at com.karumi.dexter.DexterInstance.checkMultiplePermissions(DexterInstance.java:327)
                                                                                      at com.karumi.dexter.DexterInstance.checkPermissions(DexterInstance.java:98)
                                                                                      at com.karumi.dexter.Dexter.check(Dexter.java:107)
                                                                                      at com.wmt.android.sterlingaccurisapp.fragment.BaseMultiPermissionFragment.checkPermission(BaseMultiPermissionFragment.java:71)
                                                                                      at com.wmt.android.sterlingaccurisapp.fragment.LocateLabListFragment.activityCreated(LocateLabListFragment.java:116)
                                                                                      at com.wmt.android.sterlingaccurisapp.fragment.BaseFragment.onActivityCreated(BaseFragment.java:37)
                                                                                      at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2352)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                                                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                                      at android.os.Handler.handleCallback(Handler.java:769)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                      at android.os.Looper.loop(Looper.java:164)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6535)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/data/app/com.wmt.android.sterlingaccurisapp-4dNiTvu7tdt8-SOpmSFwEg==/base.apk"],nativeLibraryDirectories=[/data/app/com.wmt.android.sterlingaccurisapp-4dNiTvu7tdt8-SOpmSFwEg==/lib/x86, /system/lib, /system/vendor/lib]]
                                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                      at com.google.android.gms.location.zzs.zza(Unknown Source:0) 
                                                                                      at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source:112) 
                                                                                      at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.init(LocationGooglePlayServicesProvider.java:83) 
                                                                                      at io.nlopez.smartlocation.SmartLocation$LocationControl.<init>(SmartLocation.java:173) 
                                                                                      at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:67) 
                                                                                      at com.wmt.android.sterlingaccurisapp.fragment.LocateLabListFragment.startLocation(LocateLabListFragment.java:460) 
                                                                                      at com.wmt.android.sterlingaccurisapp.fragment.LocateLabListFragment.permissionGiven(LocateLabListFragment.java:393) 
                                                                                      at com.wmt.android.sterlingaccurisapp.fragment.BaseMultiPermissionFragment.onPermissionsChecked(BaseMultiPermissionFragment.java:87) 
                                                                                      at com.karumi.dexter.listener.multi.CompositeMultiplePermissionsListener.onPermissionsChecked(CompositeMultiplePermissionsListener.java:54) 
                                                                                      at com.karumi.dexter.DexterInstance$1.run(DexterInstance.java:334) 
                                                                                      at com.karumi.dexter.MainThread.execute(MainThread.java:32) 
                                                                                      at com.karumi.dexter.DexterInstance.checkMultiplePermissions(DexterInstance.java:327) 
                                                                                      at com.karumi.dexter.DexterInstance.checkPermissions(DexterInstance.java:98) 
                                                                                      at com.karumi.dexter.Dexter.check(Dexter.java:107) 
                                                                                      at com.wmt.android.sterlingaccurisapp.fragment.BaseMultiPermissionFragment.checkPermission(BaseMultiPermissionFragment.java:71) 
                                                                                      at com.wmt.android.sterlingaccurisapp.fragment.LocateLabListFragment.activityCreated(LocateLabListFragment.java:116) 
                                                                                      at com.wmt.android.sterlingaccurisapp.fragment.BaseFragment.onActivityCreated(BaseFragment.java:37) 
                                                                                      at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2352) 
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442) 
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740) 
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809) 
                                                                                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799) 
                                                                                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580) 
                                                                                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367) 
                                                                                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322) 
                                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229) 
                                                                                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700) 
                                                                                      at android.os.Handler.handleCallback(Handler.java:769) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                      at android.os.Looper.loop(Looper.java:164) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6535) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by harsewaksingh13** [comment]
I fixed the problem by adding this to build.gradle:
compile 'com.google.android.gms:play-services-location:11.8.0'
