### ISSUE TITLE
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.nlopez.smartlocation.utils.Logger.d(java.lang.String, java.lang.Object[])' on a null object reference

### ISSUE THREAD

**Issue by metao1** [mrmans0n/smart-location-lib#235]
Hello,
I get this error when trying to close the provider :

Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.nlopez.smartlocation.utils.Logger.d(java.lang.String, java.lang.Object[])' on a null object reference
                                                                     at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.stop(LocationGooglePlayServicesProvider.java:171)
                                                                     at it.wetaxi.share.managers.LocationUpdateManager.stop(LocationUpdateManager.java:210)
                                                                     at it.wetaxi.share.managers.LocationUpdateManager.switchGps(LocationUpdateManager.java:189)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at

**Comment by yashpalraj** [comment]
I am facing the same Error.

Any Solution?
