### ISSUE TITLE
Crash: provider doesn't exist: network

### ISSUE THREAD

**Issue by sashatrn** [mrmans0n/smart-location-lib#24]
I tried to test library v. 2.0.8 with Android emulator 4.4.2 without Google API. If additional info is required please ask.

01-01 13:16:04.431    2187-2205/com.trukom.livegps E/SmartLocationOptions﹕ GMS not found or there were errors connecting. Disabling fused providers and activity recognizers to avoid app-breaking exceptions
01-01 13:16:04.431    2187-2205/com.trukom.livegps V/SmartLocationService﹕ old - Trying with network
01-01 13:16:35.742    2187-2205/com.trukom.livegps E/AndroidRuntime﹕ FATAL EXCEPTION: ServiceStartArguments
    Process: com.trukom.livegps, PID: 2187
    java.lang.IllegalArgumentException: provider doesn't exist: network
            at android.os.Parcel.readException(Parcel.java:1469)
            at android.os.Parcel.readException(Parcel.java:1419)
            at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:540)
            at android.location.LocationManager.requestLocationUpdates(LocationManager.java:860)
            at android.location.LocationManager.requestLocationUpdates(LocationManager.java:454)
            at io.nlopez.smartlocation.SmartLocationService.setLocationRequestValues(SmartLocationService.java:218)
            at io.nlopez.smartlocation.SmartLocationService.setOptions(SmartLocationService.java:186)
            at io.nlopez.smartlocation.SmartLocation.setOptions(SmartLocation.java:165)
            at io.nlopez.smartlocation.SmartLocation.start(SmartLocation.java:109)
            at io.nlopez.smartlocation.SmartLocation.start(SmartLocation.java:97)
            at ...

**Comment by sashatrn** [comment]
I solved the issue with following code:

		boolean networkProviderExists = false;
		if (locationManager.getAllProviders().contains("network")) {
			networkProviderExists = true;
		}
		SmartLocationOptions options = new SmartLocationOptions();
		if (!networkProviderExists) {
			options.setDefaultUpdateStrategy(UpdateStrategy.NAVIGATION);
		}
		SmartLocation.getInstance().start(this, options,
				new SmartLocation.OnLocationUpdatedListener() {
					@Override
					public void onLocationUpdated(Location location, DetectedActivity detectedActivity) {
						. . .
					}
				});

**Comment by mrmans0n** [comment]
This won't happen in 3.0.0 version :dancer:
