### ISSUE TITLE
Crash: NoClassDefFoundError: com.google.android.gms.location.LocationClient

### ISSUE THREAD

**Issue by sashatrn** [mrmans0n/smart-location-lib#25]
Crashed in Emulator with Android 4.4.2 without Google API. Library version is 2.0.8.

01-07 11:32:17.158    2449-2449/com.trukom.livegps E/SmartLocationOptions﹕ GMS not found or there were errors connecting. Disabling fused providers and activity recognizers to avoid app-breaking exceptions
01-07 11:32:17.158    2449-2449/com.trukom.livegps E/dalvikvm﹕ Could not find class 'com.google.android.gms.location.LocationClient', referenced from method io.nlopez.smartlocation.SmartLocationService.initLocation
01-07 11:32:17.158    2449-2449/com.trukom.livegps W/dalvikvm﹕ VFY: unable to resolve new-instance 4252 (Lcom/google/android/gms/location/LocationClient;) in Lio/nlopez/smartlocation/SmartLocationService;
01-07 11:32:17.158    2449-2449/com.trukom.livegps D/dalvikvm﹕ VFY: replacing opcode 0x22 at 0x0000
01-07 11:32:17.158    2449-2449/com.trukom.livegps I/dalvikvm﹕ Could not find method com.google.android.gms.location.LocationClient.isConnected, referenced from method io.nlopez.smartlocation.SmartLocationService.startOldSchoolLocation
01-07 11:32:17.158    2449-2449/com.trukom.livegps W/dalvikvm﹕ VFY: unable to resolve virtual method 28692: Lcom/google/android/gms/location/LocationClient;.isConnected ()Z
01-07 11:32:17.168    2449-2449/com.trukom.livegps D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x005b
01-07 11:32:17.168    2449-2449/com.trukom.livegps I/dalvikvm﹕ Could not find method com.google.android.gms.location.LocationClient.isConnected, referenced from method io.nlopez.smartlocation.SmartLocationService.startLocation
01-07 11:32:17.168    2449-2449/com.trukom.livegps W/dalvikvm﹕ VFY: unable to resolve virtual method 28692: Lcom/google/android/gms/location/LocationClient;.isConnected ()Z
01-07 11:32:17.168    2449-2449/com.trukom.livegps D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0016
01-07 11:32:17.168    2449-2449/com.trukom.livegps I/dalvikvm﹕ Could not find method com.google.android.gms.location.LocationClient.isConnected, referenced from method io.nlopez.smartlocation.SmartLocationService.startLocation
01-07 11:32:17.168    2449-2449/com.trukom.livegps W/dalvikvm﹕ VFY: unable to resolve virtual method 28692: Lcom/google/android/gms/location/LocationClient;.isConnected ()Z
01-07 11:32:17.168    2449-2449/com.trukom.livegps D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x004e
01-07 11:32:17.168    2449-2449/com.trukom.livegps I/dalvikvm﹕ Could not find method com.google.android.gms.location.LocationClient.isConnected, referenced from method io.nlopez.smartlocation.SmartLocationService.stopLocation
01-07 11:32:17.168    2449-2449/com.trukom.livegps W/dalvikvm﹕ VFY: unable to resolve virtual method 28692: Lcom/google/android/gms/location/LocationClient;.isConnected ()Z
01-07 11:32:17.168    2449-2449/com.trukom.livegps D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
01-07 11:32:17.168    2449-2449/com.trukom.livegps D/dalvikvm﹕ DexOpt: unable to opt direct call 0x7011 at 0x02 in Lio/nlopez/smartlocation/SmartLocationService;.initLocation
01-07 11:32:17.168    2449-2449/com.trukom.livegps D/AndroidRuntime﹕ Shutting down VM
01-07 11:32:17.168    2449-2449/com.trukom.livegps W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0xb2d2eb20)
01-07 11:32:17.198    2449-2449/com.trukom.livegps D/dalvikvm﹕ GC_FOR_ALLOC freed 292K, 10% free 3421K/3768K, paused 16ms, total 17ms
01-07 11:32:17.198    2449-2449/com.trukom.livegps E/com.trukom.logger.LoggerHelper﹕ Uncaught exception
    java.lang.NoClassDefFoundError: com.google.android.gms.location.LocationClient
            at io.nlopez.smartlocation.SmartLocationService.initLocation(SmartLocationService.java:90) ~[na:0.0]
            at io.nlopez.smartlocation.SmartLocationService.onCreate(SmartLocationService.java:75) ~[na:0.0]
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2572) ~[na:0.0]
            at android.app.ActivityThread.access$1800(ActivityThread.java:135) ~[na:0.0]
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) ~[na:0.0]
            at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
            at android.os.Looper.loop(Looper.java:136) ~[na:0.0]
            at android.app.ActivityThread.main(ActivityThread.java:5017) ~[na:0.0]
            at java.lang.reflect.Method.invokeNative(Native Method) ~[na:0.0]
            at java.lang.reflect.Method.invoke(Method.java:515) ~[na:0.0]
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) ~[na:0.0]
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) ~[na:0.0]
            at dalvik.system.NativeStart.main(Native Method) ~[na:0.0]
01-07 11:32:17.208    2449-2449/com.trukom.livegps E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.trukom.livegps, PID: 2449
    java.lang.NoClassDefFoundError: com.google.android.gms.location.LocationClient
            at io.nlopez.smartlocation.SmartLocationService.initLocation(SmartLocationService.java:90)
            at io.nlopez.smartlocation.SmartLocationService.onCreate(SmartLocationService.java:75)
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2572)
            at android.app.ActivityThread.access$1800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mrmans0n** [comment]
This should be fixed in the released 3.0.0 version.
