### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by ultraon** [mrmans0n/smart-location-lib#28]
Hi, if we call SmartLocation.with(context).location().start(null) with null listener, we will get NPE:
```java
java.lang.NullPointerException
            at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.onLocationChanged(LocationGooglePlayServicesProvider.java:147)
            at com.google.android.gms.internal.nj$a.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:107)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5371)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mrmans0n** [comment]
This fix will be ready in 3.0.1 version. I will upload it as soon as possible! :)
