### ISSUE TITLE
Getting crash: java.lang.IllegalStateException: GoogleApiClient is not connected yet.

### ISSUE THREAD

**Issue by tashariko** [mrmans0n/smart-location-lib#281]
We are using version 3.3.3.
Getting this crash in our project.

> Fatal Exception: java.lang.IllegalStateException: GoogleApiClient is not connected yet.
       at com.google.android.gms.common.api.internal.zaaf.zab(zaaf.java:134)
       at com.google.android.gms.common.api.internal.zaaz.zab(zaaz.java:23)
       at com.google.android.gms.common.api.internal.zaar.execute(zaar.java:71)
       at com.google.android.gms.internal.location.zzae.addGeofences(zzae.java:6)
       at com.google.android.gms.internal.location.zzae.addGeofences(zzae.java:5)
       at io.nlopez.smartlocation.geofencing.providers.GeofencingGooglePlayServicesProvider.onConnected(GeofencingGooglePlayServicesProvider.java:202)
       at com.google.android.gms.common.internal.zaj.zaa(zaj.java:30)
       at com.google.android.gms.common.api.internal.zaar.zaa(zaar.java:295)
       at com.google.android.gms.common.api.internal.zaaf.zaf(zaaf.java:130)
       at com.google.android.gms.common.api.internal.zaaf.zaa(zaaf.java:108)
       at com.google.android.gms.common.api.internal.zaaz.onConnected(zaaz.java:105)
       at com.google.android.gms.common.api.internal.zaq.onConnected(zaq.java:5)
       at com.google.android.gms.common.internal.zah.onConnected(zah.java:2)
       at com.google.android.gms.common.internal.BaseGmsClient$zzf.zza(BaseGmsClient.java:24)
       at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(BaseGmsClient.java:12)
       at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzc(BaseGmsClient.java:11)
       at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(BaseGmsClient.java:49)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at com.google.android.gms.internal.common.zzi.dispatchMessage(zzi.java:8)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by elfiservice** [comment]
hi @tashariko could you tell me if did you fix this ? I'm facing this same problem right now tks
