### ISSUE TITLE
java.lang.IllegalArgumentException:: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by khoshbin** [mrmans0n/smart-location-lib#283]
Hi , there is problem in newer android versions
<html><body>

Strongly consider using  FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on  the PendingIntent being mutable, e.g. if it needs to be used with inline  replies or bubbles.
--
2	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
3	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:752)
4	at android.app.PendingIntent.getService(PendingIntent.java:714)
5 	at  io.nlopez.smartlocation.geofencing.providers.GeofencingGooglePlayServicesProvider.init(GeofencingGooglePlayServicesProvider.java:86)
6	at io.nlopez.smartlocation.SmartLocation$GeofencingControl.&lt;init&gt;(SmartLocation.java:377)
7	at io.nlopez.smartlocation.SmartLocation.geofencing(SmartLocation.java:108)
8	at io.nlopez.smartlocation.SmartLocation.geofencing(SmartLocation.java:100)

**Comment by Usama7666** [comment]
facing same issue

**Comment by owaisalam12** [comment]
@khoshbin @Usama7666  Did you find any solution?

**Comment by WalidFekry** [comment]
facing same issue :"(

**Comment by usergoodvery** [comment]
Just replace every instance of PendingIntent.FLAG_UPDATE_CURRENT with PendingIntent.FLAG_MUTABLE|PendingIntent.FLAG_UPDATE_CURRENT

**Comment by christocracy** [comment]
This plugin has supported this flag for over a year.  

Any reported references to this issue are due either to your own AndroidManifest or some other plugin.

this plugin is complied with SDK 33.
