### ISSUE TITLE
Criteria accuracy used incorrectly

### ISSUE THREAD

**Issue by consp1racy** [mrmans0n/smart-location-lib#29]
I am getting the following error:

``` 
Caused by: java.lang.IllegalArgumentException: accuracy=3
            at android.location.Criteria.setAccuracy(Criteria.java:223)
            at io.nlopez.smartlocation.location.providers.LocationManagerProvider.getProvider(LocationManagerProvider.java:82)
            at io.nlopez.smartlocation.location.providers.LocationManagerProvider.start(LocationManagerProvider.java:45)
            at io.nlopez.smartlocation.SmartLocation$LocationControl.start(SmartLocation.java:130)
```

Suggested solution: http://stackoverflow.com/a/16439378/2444099

**Comment by mrmans0n** [comment]
Oh, good catch.

Thank you for the suggested solution!

This is fixed in the version 3.0.2 which I have just submitted. It will be in maven central in a couple of hours.
