### ISSUE TITLE
GoogleApiClient is not connected yet, same problem on #26, #27.

### ISSUE THREAD

**Issue by Laeyoung** [mrmans0n/smart-location-lib#32]
After following this scenario, you may show same error on your phone.
1. Launch smart-location-lib sample app.
2. Click "Start Location!" button.
3. Click home button on your phone.
4. And relaunch the sample app. 

client.isConnected() returned false on startUpdating method in LocationGooglePlayServicesProvider.java. And then, GoogleApiClient returned this exception; FATAL EXCEPTION: main java.lang.IllegalStateException: GoogleApiClient is not connected yet.

I dont' understand why It happened.

02-04 14:11:18.381    8232-8232/com.andando.video E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalStateException: GoogleApiClient is not connected yet.
            at com.google.android.gms.internal.jx.a(Unknown Source)
            at com.google.android.gms.common.api.c.b(Unknown Source)
            at com.google.android.gms.internal.nb.requestActivityUpdates(Unknown Source)
            at io.nlopez.smartlocation.activity.providers.ActivityGooglePlayServicesProvider.startUpdating(ActivityGooglePlayServicesProvider.java:85)
            at io.nlopez.smartlocation.activity.providers.ActivityGooglePlayServicesProvider.onConnected(ActivityGooglePlayServicesProvider.java:115)
            at com.google.android.gms.internal.jm.f(Unknown Source)
            at com.google.android.gms.common.api.c.gJ(Unknown Source)
            at com.google.android.gms.common.api.c.d(Unknown Source)
            at com.google.android.gms.common.api.c$2.onConnected(Unknown Source)
            at com.google.android.gms.internal.jm.f(Unknown Source)
            at com.google.android.gms.internal.jm.dU(Unknown Source)
            at com.google.android.gms.internal.jl$h.b(Unknown Source)
            at com.google.android.gms.internal.jl$h.g(Unknown Source)
            at com.google.android.gms.internal.jl$b.hy(Unknown Source)
            at com.google.android.gms.internal.jl$a.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by Laeyoung** [comment]
It seem to be occured from activityRecognition.
