### ISSUE TITLE
Update to Google Play Services 7.0.0

### ISSUE THREAD

**Issue by biokys** [mrmans0n/smart-location-lib#53]

**Comment by firoze** [comment]
Yep this is probably necessary. But for now, I've been able to work around it by:

```
compile 'com.google.android.gms:play-services-location:7.0.0'
compile('io.nlopez.smartlocation:library:3.0.7') {
        exclude group:'com.google.android.gms', module:'play-services-location'
}
```

**Comment by mrmans0n** [comment]
It's a proper workaround. I recommend anybody interested uses that for the time being. I will be able to push a new update soon, meanwhile this will suffice :smile:

**Comment by biokys** [comment]
thx guys...

**Comment by biokys** [comment]
still getting this stacktrace:

Process: com.droid4you.application.wallet, PID: 21223
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoClassDefFoundError: io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider
            at io.nlopez.smartlocation.SmartLocation$LocationControl.<init>(SmartLocation.java:106)
            at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:47)
            at com.droid4you.application.wallet.v3.ui.NewRecordActivity.processLocation(NewRecordActivity.java:626)
            at com.droid4you.application.wallet.v3.ui.NewRecordActivity.saveInternally(NewRecordActivity.java:617)
            at com.droid4you.application.wallet.v3.ui.NewRecordActivity.access$1000(NewRecordActivity.java:84)
            at com.droid4you.application.wallet.v3.ui.NewRecordActivity$10.doInBackground(NewRecordActivity.java:580)
            at com.droid4you.application.wallet.v3.ui.NewRecordActivity$10.doInBackground(NewRecordActivity.java:577)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by mrmans0n** [comment]
I have just recently sent the 3.0.8 version of the library to Maven Central with 7.0.0 play services version. I am also submitting a 3.0.9-SNAPSHOT version with the 7.3.0 version of the play services, this one in the snapshot repository of maven central.
