### ISSUE TITLE
Error receiving broadcast Intent

### ISSUE THREAD

**Issue by ppamorim** [mrmans0n/smart-location-lib#64]
I installed the Fabric(Crashlytics) and was return this error.

    java.lang.RuntimeException: Error receiving broadcast Intent { act=io.nlopez.smartlocation.geocoding.providers.AndroidGeocodingProvider.REVERSE_GEOCODE_ACTION flg=0x10 (has extras) } in io.nlopez.smartlocation.geocoding.providers.AndroidGeocodingProvider$2@3f47a19f
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:880)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5312)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
    Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.hi.app.fragment.MapFragment.configLocation(MapFragment.java:322)
       at com.hi.app.fragment.MapFragment.access$300(MapFragment.java:80)
       at com.hi.app.fragment.MapFragment$13.onAddressResolved(MapFragment.java:282)
       at io.nlopez.smartlocation.geocoding.providers.AndroidGeocodingProvider$2.onReceive(AndroidGeocodingProvider.java:136)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:870)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5312)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by mrmans0n** [comment]
That seems to be an error on your end. Check your onAddressResolved callback; you are assuming that at least one Address will be returned, which is not true: the array of addresses could be empty.

**Comment by ppamorim** [comment]
at io.nlopez.smartlocation.geocoding.providers.AndroidGeocodingProvider$2.onReceive(AndroidGeocodingProvider.java:136)

This can be verified at the library and add a callback to it?

**Comment by mrmans0n** [comment]
I don't think it's worth it, as the empty array it is a perfectly valid result. It should be checked in the callback IMO if that's a special case in your app.

**Comment by Eappschange9** [comment]
Sir i am facing this issue too. if i check arraylist result!=true can this codition solve my crash? how to remove this crash i stuck with that what to do now
