### ISSUE TITLE
Problem when calling in SyncAdapter

### ISSUE THREAD

**Issue by mindrunner** [mrmans0n/smart-location-lib#66]
I am trying to get the most recent location in my sync adapter. Usually this seems to work fine. However sometimes this exception is thrown. Is this a known problem? What can I do to prevent it? Is there a best practice to get location updates in background. It must not necessarily be the sync adapter, but it should be a service detached from my the Activity. And of course without draining battery!
```
Can't create handler inside thread that has not called Looper.prepare()
java.lang.IllegalStateException: Can't create handler inside thread that has not called Looper.prepare()
        at com.google.android.gms.common.internal.zzu.zza(Unknown Source)
        at com.google.android.gms.location.internal.zzi$zzc.<init>(Unknown Source)
        at com.google.android.gms.location.internal.zzi.zza(Unknown Source)
        at com.google.android.gms.location.internal.zzi.zza(Unknown Source)
        at com.google.android.gms.location.internal.zzj.zza(Unknown Source)
        at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
        at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
        at com.google.android.gms.common.api.zza$zza.zzb(Unknown Source)
        at com.google.android.gms.common.api.zzd.zza(Unknown Source)
        at com.google.android.gms.common.api.zzd.zzb(Unknown Source)
        at com.google.android.gms.common.api.zzg.zzb(Unknown Source)
        at com.google.android.gms.location.internal.zzd.requestLocationUpdates(Unknown Source)
        at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.startUpdating(LocationGooglePlayServicesProvider.java:117)
        at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.start(LocationGooglePlayServicesProvider.java:103)
        at io.nlopez.smartlocation.SmartLocation$LocationControl.start(SmartLocation.java:186)
        at com.xxx.android.sync.xxxSyncAdapter.initLocation(xxxSyncAdapter.java:180)
        at com.xxx.android.sync.xxxSyncAdapter.onPerformSync(xxxSyncAdapter.java:453)
        at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

**Comment by mrmans0n** [comment]
I am using the library in a few apps by doing the location updates inside a long running Service and never encountered that problem (for a navigation app). Never did that in a SyncAdapter though. 

The offending line seems to be code within the play services:
```java
LocationServices.FusedLocationApi.requestLocationUpdates(...)
```

For your specific case, I am thinking along the lines of creating an IntentService, fired by an AlarmManager, which will make the call to `SmartLocation.with(this).location().oneFix().start(...)` and using a [CountDownLatch](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CountDownLatch.html) to make the async location getting to be synchronous with the IntentService's thread and do your stuff when you got the location data. Also, because it can be problematic to be 100% sure that you are going to get a location on time, I would also add some sort of timeout to the location call. 

About the battery consumption, well it all depends on the frequency of the updates and the values you put on the config. I guess a best effort location get every hour or so wouldn't affect the battery life much.

**Comment by mindrunner** [comment]
I checked out the AlarmManager. This is kind of an periodic task then. I am
actually looking for some location triggered thing. Something like the OS
informs me about a "significant" location change. Is google offering
something like this? Everything else is kind of useless. If I am home all
day, we do not need to wake up my phone to send a new location to the
server. If I am moving, I want to keep track of this movements. Not exact
like activity tracking does. But I need to know where about the User is all
the time.

**Comment by mrmans0n** [comment]
Well, it depends. You can either play a bit with the activity tracking or the geofences for that, but most probably you will have to wake the phone anyway.

**Comment by mindrunner** [comment]
Apple said:
> The significant-change location service provides accuracy that’s good enough for most apps and represents a power-saving alternative to the standard location service. The service uses Wi-Fi to determine the user’s location and report changes in that location, allowing the system to manage power usage much more aggressively than it could otherwise. The significant-change location service can also wake up an iOS app that is currently suspended or not running in order to deliver new location data.

This is what is possible on iOS SDK
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html

Is there really no google equivalent?

**Comment by mrmans0n** [comment]
Not that I know of, no.
