### ISSUE TITLE
java.lang.IllegalArgumentException at android 2.3.4

### ISSUE THREAD

**Issue by 2rba** [mrmans0n/smart-location-lib#69]
SmartLocation.with(context).location()
                        .config(LocationParams.NAVIGATION)
                        .provider(new LocationGooglePlayServicesWithFallbackProvider(context))
                        .start(
fires java.lang.IllegalArgumentException if GPS is turned off (android 4.4.2 is ok)

java.lang.IllegalArgumentException: no providers found for criteria
	at android.os.Parcel.readException(Parcel.java:1326)
	at android.os.Parcel.readException(Parcel.java:1276)
	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:646)
	at android.location.LocationManager._requestLocationUpdates(LocationManager.java:582)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:563)
	at io.nlopez.smartlocation.location.providers.LocationManagerProvider.start(LocationManagerProvider.java:51)
	at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.start(LocationGooglePlayServicesWithFallbackProvider.java:54)
	at io.nlopez.smartlocation.SmartLocation$LocationControl.start(SmartLocation.java:186)

**Comment by UglyTroLL** [comment]
+1

**Comment by UglyTroLL** [comment]
It happens when there is no location provider available on users' device, guess we need to catch the issue at https://github.com/mrmans0n/smart-location-lib/blob/a899f3504e7f375975aabf348bc5809195a44b41/library/src/main/java/io/nlopez/smartlocation/location/providers/LocationManagerProvider.java#L51 or change the interface API to throw IllegalArgumentException to let developer handle this.
