### ISSUE TITLE
NullPointerException at AndroidGeocodingProvider

### ISSUE THREAD

**Issue by ppamorim** [mrmans0n/smart-location-lib#75]
Bugsnag returns:

    java.lang.NullPointerException: locale == null
        at android.location.Geocoder.<init>(Geocoder.java:81)
        at io.nlopez.smartlocation.geocoding.providers.AndroidGeocodingProvider$AndroidGeocodingService.    onHandleIntent(AndroidGeocodingProvider.java:154)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.os.HandlerThread.run(HandlerThread.java:60)

That's all.

**Comment by mrmans0n** [comment]
I have added an extra check for this in version 3.2.0. Anyway I have looked it up a little bit and locale being null is very very strange, as it should never happen. I think it might be one of those android oddities in weird statuses...
