### ISSUE TITLE
NoClassDefFoundError Api$ClientKey

### ISSUE THREAD

**Issue by int-00h** [mrmans0n/smart-location-lib#80]
compileSdkVersion 23
buildToolsVersion "23"

```
compile 'com.google.android.gms:play-services-gcm:7.5.0'
compile ('io.nlopez.smartlocation:library:3.0.11') {
    transitive = true;
}
```

    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$ClientKey;
            at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source)
            at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.init(LocationGooglePlayServicesProvider.java:58)
            at io.nlopez.smartlocation.SmartLocation$LocationControl.<init>(SmartLocation.java:140)
            at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:59)

**Comment by Swisyn** [comment]
same error here

**Comment by mrmans0n** [comment]
This is a clone of #87. Anyway I have just submitted version 3.2.0 to maven central which solves this. It uses Play Services 8.1.0.
