### ISSUE TITLE
Crashlytics reports NullPointerException in GeofencingGooglePlayServicesProvider line 246

### ISSUE THREAD

**Issue by erf** [mrmans0n/smart-location-lib#86]
I got the following crash report from Crashlytics (Android 2.3.4):
<pre>
java.lang.NullPointerException
       at io.nlopez.smartlocation.geofencing.providers.GeofencingGooglePlayServicesProvider$GeofencingService.onHandleIntent(GeofencingGooglePlayServicesProvider.java:246)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:59)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:130)
       at android.os.HandlerThread.run(HandlerThread.java:60)
</pre>
<pre>
thread
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1429)
       at java.lang.LangAccessImpl.parkFor(LangAccessImpl.java:48)
       at sun.misc.Unsafe.park(Unsafe.java:337)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:228)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1021)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1081)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
       at java.lang.Thread.run(Thread.java:1019)
</pre>

**Comment by NorbertSzydlowski** [comment]
+1

**Comment by YuriHeupa** [comment]
+1

**Comment by rohanmahale** [comment]
+1

**Comment by erf** [comment]
started working on my own location library -> https://github.com/erf/locate
It's very new and minimal but maybe it will solve someones problem.

**Comment by mrmans0n** [comment]
This has been fixed in 3.2.1

**Comment by Aiuspaktyn** [comment]
3.2.5 same problem :(

**Comment by skmlcd** [comment]
**Crashlytics report**
Device: Android on Emulator (that is probably [Google's Monkey test](https://developer.android.com/studio/test/monkey.html))
Version: 4.1.1

```
Fatal Exception: java.lang.NullPointerException
       at io.nlopez.smartlocation.geofencing.providers.GeofencingGooglePlayServicesProvider$GeofencingService.onHandleIntent(GeofencingGooglePlayServicesProvider.java:271)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```
