### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$ClientKey"

### ISSUE THREAD

**Issue by forlayo** [mrmans0n/smart-location-lib#88]
Hello gentleman,

I'm getting didn't find class exception when I try to use your library:
```java
09-25 14:56:48.202  23206-23206/com.example E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example, PID: 23206
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$ClientKey;
            at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source)
            at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.init(LocationGooglePlayServicesProvider.java:58)
            at io.nlopez.smartlocation.SmartLocation$LocationControl.<init>(SmartLocation.java:140)
            at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:59)
            at com.example.activities.ConversationActivity$PlaceholderFragment$7.onClick(ConversationActivity.java:1286)
            at android.view.View.performClick(View.java:5156)
            at android.view.View$PerformClick.run(View.java:20755)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5832)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$ClientKey" on path: DexPathList[[zip file "/data/app/com.example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example-1/lib/arm, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source)
            at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.init(LocationGooglePlayServicesProvider.java:58)
            at io.nlopez.smartlocation.SmartLocation$LocationControl.<init>(SmartLocation.java:140)
            at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:59)
            at com.example.activities.ConversationActivity$PlaceholderFragment$7.onClick(ConversationActivity.java:1286)
            at android.view.View.performClick(View.java:5156)
            at android.view.View$PerformClick.run(View.java:20755)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5832)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
    Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.api.Api$ClientKey
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 16 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

I'm using:
```
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.android.support:support-v4:23.0.0'
    compile 'com.android.support:design:23.0.0'
    compile 'com.android.support:recyclerview-v7:23.0.0'
    compile 'com.google.android.gms:play-services-base:7.8.0'
    compile 'com.google.android.gms:play-services-gcm:7.8.0'
    compile 'com.google.android.gms:play-services-maps:7.8.0'
```

And compiling with:
```
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
```

Thanks a lot for your work., Regards

**Comment by mrmans0n** [comment]
This is a clone of #87. I am closing this one.
