### ISSUE TITLE
MainActivity has leaked IntentReceiver io.nlopez.smartlocation.geocoding.providers.AndroidGeocodingProvider that was originally registered here. Are you missing a call to unregisterReceiver()?

### ISSUE THREAD

**Issue by Twibit** [mrmans0n/smart-location-lib#91]
I get this error when i quit my app after using SmartLocation.with(context).geocoding().direct().
To avoid the problem, i need to call SmartLocation.with(MainActivity.this).geocoding().stop() in the callback.

```
E/ActivityThread: Activity com.twibit.app.ui.activity.MainActivity has leaked IntentReceiver io.nlopez.smartlocation.geocoding.providers.AndroidGeocodingProvider$1@10817f08 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread: android.app.IntentReceiverLeaked: Activity com.twibit.app.ui.activity.MainActivity has leaked IntentReceiver io.nlopez.smartlocation.geocoding.providers.AndroidGeocodingProvider$1@10817f08 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread:     at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:907)
E/ActivityThread:     at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:708)
E/ActivityThread:     at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1771)
E/ActivityThread:     at android.app.ContextImpl.registerReceiver(ContextImpl.java:1751)
E/ActivityThread:     at android.app.ContextImpl.registerReceiver(ContextImpl.java:1745)
E/ActivityThread:     at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:488)
E/ActivityThread:     at io.nlopez.smartlocation.geocoding.providers.AndroidGeocodingProvider.start(AndroidGeocodingProvider.java:96)
E/ActivityThread:     at io.nlopez.smartlocation.SmartLocation$GeocodingControl.start(SmartLocation.java:303)
E/ActivityThread:     at io.nlopez.smartlocation.SmartLocation$GeocodingControl.start(SmartLocation.java:279)
E/ActivityThread:     at io.nlopez.smartlocation.SmartLocation$GeocodingControl.direct(SmartLocation.java:251)
E/ActivityThread:     at com.twibit.app.ui.activity.MainActivity.loadNewData(MainActivity.java:267)
E/ActivityThread:     at com.twibit.app.ui.activity.MainActivity.updateData(MainActivity.java:197)
E/ActivityThread:     at com.twibit.app.ui.activity.MainActivity.onResume(MainActivity.java:117)
E/ActivityThread:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1264)
E/ActivityThread:     at android.app.Activity.performResume(Activity.java:6039)
E/ActivityThread:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2978)
E/ActivityThread:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3030)
E/ActivityThread:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2393)
E/ActivityThread:     at android.app.ActivityThread.access$800(ActivityThread.java:148)
E/ActivityThread:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
E/ActivityThread:     at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityThread:     at android.os.Looper.loop(Looper.java:135)
E/ActivityThread:     at android.app.ActivityThread.main(ActivityThread.java:5312)
E/ActivityThread:     at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread:     at java.lang.reflect.Method.invoke(Method.java:372)
E/ActivityThread:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
E/ActivityThread:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

**Comment by rohannexialabs** [comment]
Hi,
I faced same issue today, the solution is to unregister the broadcast receiver. Just add the following code where you are stopping location.
``
        SmartLocation.with(MainActivity3.this).geocoding().stop();
``
eg -

    @Override
        protected void onStop() {
        super.onStop();
        SmartLocation.with(MainActivity3.this).location().stop();
        SmartLocation.with(MainActivity3.this).geocoding().stop();
        Log.d("MainActivity", "Stopping the location service");

    }

**Comment by mrmans0n** [comment]
Yep, that's by design. You have to call stop when you are finished with it.

**Comment by Twibit** [comment]
Oh ok. 
That is not obvious when using SmartLocation.with(this).location().oneFix() and SmartLocation.with(context).geocoding().direct().
