### ISSUE TITLE
Crashlytics reports NullpointerException in AndroidGeocodingProvider

### ISSUE THREAD

**Issue by erf** [mrmans0n/smart-location-lib#92]
Crashlytics reports NullpointerException in AndroidGeocodingProvider (see error log below) on a Android 4 device.

I did not include 'com.google.android.gms:play-services-location:8.1.0' in the version that caused this error. Do i need it?

<pre>
java.lang.NullPointerException: locale == null
       at android.location.Geocoder.<init>(Geocoder.java:81)
       at io.nlopez.smartlocation.geocoding.providers.AndroidGeocodingProvider$AndroidGeocodingService.onHandleIntent(AndroidGeocodingProvider.java:166)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
</pre>

**Comment by mrmans0n** [comment]
You don't need play services for geocoding. This is a very weird error that only could happen in states where the actual Android OS is kinda broken, that's the only case where the locale could be null. I added in version 3.2.0 an extra check for that, but the result is the same: a RuntimeException. You should wrap this in a try/catch block to have a graceful recovery in those states, but probably will crash in other place then.
