### ISSUE TITLE
Its crashing with Google plus library

### ISSUE THREAD

**Issue by irfaan008** [mrmans0n/smart-location-lib#97]
I was really happy when I made my project worked using this library but on final testing I found that my "Goolge plus login" screen was clashing with this. I removed the google login and it worked. This was the line where the google login was crashing : 
        mGoogleApiClient = new GoogleApiClient.Builder(activity)
                .addConnectionCallbacks(this)
                .addOnConnectionFailedListener(this).addApi(Plus.API)
                .addScope(Plus.SCOPE_PLUS_LOGIN).build();

Unfortunately I didn't find a single solution of this problem on Google so left writing here.

Edit 1 : I removed the smart-location-lib and all worked fine
Edit 2 : I removed Google plus login screen and all worked fine.
Edit 3 : I have added tools:replace attribute on manifest

 <meta-data
            android:name="com.google.android.gms.version"
            tools:replace="android:value"
            android:value="@integer/google_play_services_version" />

Staketrace of error 

10-08 08:53:14.898  18895-18895/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.irinnovative.peepinnow, PID: 18895
    java.lang.NoSuchMethodError: No virtual method zzog()Landroid/accounts/Account; in class Lcom/google/android/gms/common/internal/zzf; or its super classes (declaration of 'com.google.android.gms.common.internal.zzf' appears in /data/app/com.irinnovative.peepinnow-2/base.apk)
            at com.google.android.gms.plus.Plus$1.zza(Unknown Source)
            at com.google.android.gms.plus.Plus$1.zza(Unknown Source)
            at com.google.android.gms.internal.zzli.zza(Unknown Source)
            at com.google.android.gms.internal.zzli.<init>(Unknown Source)
            at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
            at com.irinnovative.peepinnow.fragments.FragmentGoogleLogin.setupGoooglePlus(FragmentGoogleLogin.java:120)
            at com.irinnovative.peepinnow.fragments.FragmentGoogleLogin.onCreateView(FragmentGoogleLogin.java:111)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1026)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1572)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:493)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5290)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

<img width="1339" alt="screen shot 2015-10-08 at 8 47 45 am" src="https://cloud.githubusercontent.com/assets/3459406/10356957/263684c6-6d9a-11e5-8347-57e414c6995c.png">

**Comment by mrmans0n** [comment]
You would probably need to do a new Provider that handles the multiple API requests if you want to use them together. This cannot be done in a generic way for it to work as you intend, but it's okay because you can provide your own implementation :smile:

**Comment by irfaan008** [comment]
Could you please explain what do you mean by "You would probably need to do a new Provider that handles the multiple API requests if you want to use them together". FYI, I am just using this library to fetch real time location. I am not using this for geofencing, geocoding and other things. Also please guide me about the implementation you talked about.. I guess your uploaded image is corrupted.

**Comment by mozes-pb** [comment]
Hi @irfaan008 , I got the same issues and updating the version of the google play services to 8.1.0 in gradle seems to have fixed it for me.
example : compile 'com.google.android.gms:play-services-plus:8.1.0'

**Comment by tharanagaraj** [comment]
Hey @irfaan008 - Were you able to fix this? If yes, how did you? I have the exact same error.

**Comment by bsautner** [comment]
i use the google+ library along with this nice library but i have to include it in my dependencies like this: 

  compile ('io.nlopez.smartlocation:library:3.2.0') {
        transitive = false
    }

**Comment by tharanagaraj** [comment]
Got it, thanks!

**Comment by mavenave** [comment]
Btw, this also solves the my problem, in case anyone managed to Google to this rabbit hole.
```
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzqf;
```
