### ISSUE TITLE
Crashlytics reported fatal issue - AndroidGeocodingService

### ISSUE THREAD

**Issue by Seidak** [mrmans0n/smart-location-lib#99]
Hello,
I received this issue on Crashlytics.

    java.lang.NullPointerException: locale == null
       at android.location.Geocoder.<init>(Geocoder.java:81)
       at io.nlopez.smartlocation.geocoding.providers.AndroidGeocodingProvider$AndroidGeocodingService.onHandleIntent(AndroidGeocodingProvider.java:166)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:59)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:130)
       at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by mrmans0n** [comment]
This has been fixed in 3.2.1
